import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Separator } from '@/components/ui/separator'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/provider/ThemeProvider'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={cn(geistSans.variable, geistMono.variable, "dark")}
        style={{
          colorScheme: 'dark',
        }}
      >
        <body >
          <ThemeProvider>
            <div className='flex min-h-screen w-full flex-col items-center dark:bg-black'>
              <Navbar />
              <Separator />
              <main className='flex flex-grow w-full justify-center items-center dark:bg-neutral-950'>
                {children}
                <Toaster />
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}